name=input('what is your name:')
print(name)
a=input('Where do you live:')
print(a)
s=input('where are you studyin:')
print(s)
x=input('what you like to eat:')
print(x)
d=input('what drinks do you like:')
print(d)
h=input('you have a hobby:')
print(h)
m=input('what is your dream:')
print(m)